module.exports.Names = [
    "The Gourmet Kitchen",
    "Sushi Paradise",
    "Taco Haven",
    "Burger Bonanza",
    "Curry House",
    "Dragon Wok",
    "French Delights",
    "Pizza Palace",
    "Steak & Grill",
    "Seafood Shack",
    "Vegetarian Bistro",
        "La Dolce Vita", "Bella Cucina", "Trattoria Toscana", "Pasta Fresca", "Il Sapore Italiano", 
        "Le Petit Bistro", "Café de Paris", "La Belle Époque", "Bon Appétit", "Maison Fleur", 
        "The Rusty Spoon", "Urban Grill", "Sunset Diner", "The Hungry Bear", "Liberty Eats", 
        "Bamboo Garden", "Dragon's Delight", "Lotus Blossom", "Samurai Sushi", "Spice Route", 
        "El Pueblo", "Casa de Salsa", "Taqueria Fiesta", "Viva Mexico", "Cantina Corazón", 
        "The Melting Pot", "Flavor Fusion", "Global Gourmet", "Epicurean Experience", "Fusion Fare", 
        "Green Garden", "Purely Plants", "The Veggie Table", "Earthly Eats", "Herbivore Haven", 
        "Ocean's Bounty", "The Salty Sailor", "Neptune's Table", "Catch of the Day", "Sea Breeze Grill", 
        "Cozy Corner", "Café Serenity", "Hearth & Home", "The Nook Café", "Morning Glory Café", 
        "Harvest Moon", "Golden Harvest", "The Tasty Spoon", "Spice Symphony", "The Hungry Pelican", 
        "Blue Lagoon", "Silver Spoon", "Red Lantern", "Mystic Garden", "Rustic Table", 
        "Savory Skillet", "The Gracious Table", "The Golden Apple", "The Green Olive", "The Sizzling Stone", 
        "The Twisted Fork", "The Saucy Chef", "The Spicy Grill", "The Rustic Rooster", "The Hungry Hen", 
        "The Tipsy Turtle", "The Cozy Owl", "The Sleepy Dog", "The Red Fox", "The Blue Heron", 
        "The Golden Lion", "The Happy Cow", "The Dancing Goat", "The Lazy Dog", "The Tipsy Parrot", 
        "The Jolly Roger", "The Salty Dog", "The Spicy Pepper", "The Sweet Basil", "The Grumpy Chef", 
        "The Hungry Hog", "The Red Rooster", "The Blue Dolphin", "The Golden Egg", "The Green Dragon", 
        "The Sizzling Steak", "The Toasted Bread", "The Spicy Sausage", "The Savory Duck", "The Golden Goose", 
        "The Silver Swan", "The Happy Fish", "The Dancing Crab", "The Lazy Lobster", "The Spicy Shrimp", 
        "The Sweet Prawn", "The Grumpy Crab", "The Hungry Cat", "The Red Lobster", "The Blue Crab", 
        "The Golden Fish", "The Green Crab", "The Sizzling Salmon", "The Toasted Tuna", "The Spicy Scallop", 
        "The Savory Cod", "The Golden Trout", "The Silver Snapper", "The Happy Octopus", "The Dancing Squid", 
        "The Lazy Eel", "The Spicy Mackerel", "The Sweet Anchovy", "The Grumpy Tuna", "The Hungry Shark", 
        "The Red Whale", "The Blue Octopus", "The Golden Dolphin", "The Green Shark", "The Sizzling Sardine", 
        "The Toasted Herring", "The Spicy Bass", "The Savory Pike", "The Golden Perch", "The Silver Carp", 
        "The Happy Minnow", "The Dancing Guppy", "The Lazy Pike", "The Spicy Haddock", "The Sweet Sole", 
        "The Grumpy Perch", "The Hungry Trout", "The Red Bass", "The Blue Salmon", "The Golden Pike", 
        "The Green Perch", "The Sizzling Trout", "The Toasted Pike", "The Spicy Cod", "The Savory Trout", 
        "The Golden Perch", "The Silver Salmon", "The Happy Herring", "The Dancing Pike", "The Lazy Trout", 
        "The Spicy Herring", "The Sweet Salmon", "The Grumpy Trout", "The Hungry Herring", "The Red Salmon", 
        "The Blue Trout", "The Golden Herring", "The Green Salmon", "The Sizzling Trout", "The Toasted Salmon", 
        "The Spicy Herring", "The Savory Trout", "The Golden Herring", "The Silver Salmon", "The Happy Trout", 
        "The Dancing Herring", "The Lazy Salmon", "The Spicy Trout", "The Sweet Herring", "The Grumpy Salmon", 
        "The Hungry Trout", "The Red Herring", "The Blue Trout", "The Golden Salmon", "The Green Herring", 
        "The Sizzling Trout", "The Toasted Herring", "The Spicy Salmon", "The Savory Trout", "The Golden Herring", 
        "The Silver Salmon", "The Happy Trout", "The Dancing Herring", "The Lazy Salmon", "The Spicy Trout", 
        "The Sweet Herring", "The Grumpy Salmon", "The Hungry Trout", "The Red Herring", "The Blue Trout", 
        "The Golden Salmon", "The Green Herring", "The Sizzling Trout", "The Toasted Herring", "The Spicy Salmon", 
        "The Savory Trout", "The Golden Herring", "The Silver Salmon", "The Happy Trout", "The Dancing Herring", 
        "The Lazy Salmon", "The Spicy Trout", "The Sweet Herring", "The Grumpy Salmon", "The Hungry Trout", 
        "The Red Herring", "The Blue Trout", "The Golden Salmon", "The Green Herring", "The Sizzling Trout", 
        "The Toasted Herring", "The Spicy Salmon", "The Savory Trout", "The Golden Herring", "The Silver Salmon", 
        "The Happy Trout", "The Dancing Herring", "The Lazy Salmon", "The Spicy Trout", "The Sweet Herring", 
        "The Grumpy Salmon", "The Hungry Trout", "The Red Herring", "The Blue Trout", "The Golden Salmon", 
        "The Green Herring", "The Sizzling Trout", "The Toasted Herring", "The Spicy Salmon", "The Savory Trout", 
        "The Golden Herring", "The Silver Salmon", "The Happy Trout", "The Dancing Herring", "The Lazy Salmon", 
        "The Spicy Trout", "The Sweet Herring", "The Grumpy Salmon", "The Hungry Trout", "The Red Herring", 
        "The Blue Trout", "The Golden Salmon", "The Green Herring", "The Sizzling Trout", "The Toasted Herring", 
        "The Spicy Salmon", "The Savory Trout", "The Golden Herring", "The Silver Salmon", "The Happy Trout", 
        "The Dancing Herring", "The Lazy Salmon", "The Spicy Trout", "The Sweet Herring", "The Grumpy Salmon", 
        "The Hungry Trout",
    
    ];
  
  
  


